backend:
  # name: git-gateway
  branch: develop
  name: test-repo
media_folder: public/img
public_folder: img
publish_mode: editorial_workflow
collections:
  - name: "Blog Posts"
    label: "Posts"
    create: true
    identifier_field: "title"
    slug: "{{fields.slug}}"
    folder: "content"
    fields:
          - { label: "Title", name: "title", widget: "string" }
          - {label: "Slug", name: "slug", widget: "string",pattern: ['^[a-zA-Z0-9-_]+$', "Alphanumeric with dashes or underscores"]}
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "Tags"
    label: "Tags"
    create: true
    identifier_field: "title"
    slug: "{{fields.slug}}"
    folder: "content"
    fields:
          - { label: "Title", name: "title", widget: "string" }
          - {label: "Slug", name: "slug", widget: "string",pattern: ['^[a-zA-Z0-9-_]+$', "Alphanumeric with dashes or underscores"]}
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          
