backend:
  name: github
  repo: dusmel/neueux-bckp
  branch: develop
  # name: test-repo
publish_mode: editorial_workflow
media_folder: public/img
public_folder: img
collections:
  - name: "content"
    label: "Content"
    create: true
    folder: "content"
    fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "tag"
    label: "tag"
    create: true
    folder: "content"
    fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "Communities"
    label: "communities"
    extension: "json"
    files:
      - file: "public/communities.json"
        label: "Communities"
        name: "communities"
        widget: "list"
        fields:
          - { name: "body", label: "Body", widget: "string" }
          - { name: "portal", label: "Portal", widget: "string" }
          - { name: active, label: Active, widget: "boolean" }
          
